# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the Node.js 16.x image as the base image
FROM node:16-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Create a release image
FROM node:16-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built files and package.json
COPY --from=build /app/build /app/build
COPY --from=build /app/package.json /app/package.json

# Install production dependencies only
RUN npm install --production

# Set the command to run the application
ENTRYPOINT ["node", "build/index.js"]
